---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tandoor
  namespace: tandoor
  labels: &labels
    app.kubernetes.io/name: tandoor
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels: *labels
  template:
    metadata:
      # annotations:
      #   backup.velero.io/backup-volumes: media,static
      labels: *labels
    spec:
      restartPolicy: Always
      initContainers:
        - name: init-chmod-data
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: tandoor
                  key: secret-key
            - name: DB_ENGINE
              value: django.db.backends.postgresql
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-tandoor
                  key: HOST
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-tandoor
                  key: LOGIN
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-tandoor
                  key: DATABASE_NAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-tandoor
                  key: PASSWORD
          image: vabene1111/recipes
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 250m
              memory: 64Mi
          command:
            - sh
            - -c
            - |
              set -e
              source venv/bin/activate
              echo "Updating database"
              python manage.py migrate
              python manage.py collectstatic --noinput
              echo "Setting media file attributes"
              chown -R 65534:65534 /opt/recipes/mediafiles
              find /opt/recipes/mediafiles -type d | xargs -r chmod 755
              find /opt/recipes/mediafiles -type f | xargs -r chmod 644
              echo "Done"
          securityContext:
            runAsUser: 0
          volumeMounts:
            - mountPath: /opt/recipes/mediafiles
              name: data
              subPath: media/files
            - mountPath: /opt/recipes/staticfiles
              name: data
              subPath: static/files
      containers:
        - name: tandoor-nginx
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
              name: http
          resources:
            requests:
              cpu: 250m
              memory: 64Mi
          volumeMounts:
            - mountPath: /media
              name: data
              subPath: media/files
            - mountPath: /static
              name: data
              subPath: static/files
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx-config
              readOnly: true
        - name: tandoor
          image: vabene1111/recipes
          imagePullPolicy: IfNotPresent
          command:
            - /opt/recipes/venv/bin/gunicorn
            - -b
            - :8080
            - --access-logfile
            - "-"
            - --error-logfile
            - "-"
            - --log-level
            - INFO
            - recipes.wsgi
          ports:
            - containerPort: 8080
              protocol: TCP
              name: gunicorn
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            periodSeconds: 30
          resources:
            requests:
              cpu: 250m
              memory: 64Mi
          volumeMounts:
            - mountPath: /opt/recipes/mediafiles
              name: data
              # mount as subPath due to lost+found on ext4 pvc
              subPath: media/files
            - mountPath: /opt/recipes/staticfiles
              name: data
              # mount as subPath due to lost+found on ext4 pvc
              subPath: static/files
          env:
            - name: DEBUG
              value: "0"
            - name: ALLOWED_HOSTS
              value: "*"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: tandoor
                  key: secret-key
            - name: GUNICORN_MEDIA
              value: "0"
            - name: DB_ENGINE
              value: django.db.backends.postgresql
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-tandoor
                  key: HOST
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-tandoor
                  key: LOGIN
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-tandoor
                  key: DATABASE_NAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-tandoor
                  key: PASSWORD
            - name: FDC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: tandoor
                  key: fdc-api-key
            - name: SOCIAL_PROVIDERS
              value: allauth.socialaccount.providers.openid_connect
          securityContext:
            runAsUser: 65534
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
        - name: nginx-config
          configMap:
            name: nginx-config
