apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc.yaml
  - postgres.yaml
  - nginx-config.yaml
  - secrets.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
