---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: tandoor
  labels:
    app.kubernetes.io/name: tandoor
    app.kubernetes.io/component: media-pvc
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
