---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tandoor
  namespace: tandoor
spec:
  encryptedData:
    fdc-api-key: AgBYwdiCzOvLXNi3ESuDyiRazCnoxA4lLomF9yJaDIc/j93Go8RQW36ldranDa8v2k+f++jkzkLJwPYd+Zfo+M/bo1g1BM8g1QKKudAs0+iE5J4MK3+0ypzWX44p74xVlkVnQEMuKtJaMRLWcZ+PdfCE1+vebZx8QcKkNLkq6XzkAFY2tGbCFB07mWy6uymwpgQSsT2UR743RTTv7qlSHQJtPOD2tn/hg6NVMeCc9Nq3j/m8kbftGg6grKzmwnofZ3AMbuBP0seZy0sJsWHtMPLQj+24XnRT7CYktY5XKSsGphy7VoVF/SoccTNJyLWTvPPRlLVX/5NCx+33w8shbYW0ggkMelH/2LFY88fLNi+VW0Duw6UTJV/YaLbtrI6an7Mm3wfoRKhXNZhvXiPScS1wc7qCUXyKeohPqIiTW50K6J/xhEOqNwpWYOjmNQJ2F50Htd/+T9ZbS1wE5fZXLVOqzfaB3XOY3WAX/8RUtfYQ5Dzq62aI9ktDZQfin5SF03trAyC0UKodeaPm3yqQ0lFcpoWrIoYvm91SeZdwlkhiR+ra2HBeH0V6yTRYA2YScyamTxl3QEmHOkeCYE0XOt3V0ulPynSEKBHutC89a8kOzWdqrJPj2pglPShvemA7XHyNJKXCSklSwjKyAZVbVAgCstkzeHghpuC7BZPt5PUeHU02bLMv3Mv71rqaXxltwvqrXRTlqktrDbhGgbHZlotDEJjCt99Y4xGOQmc5ndZVP4MNgH9irLue
    secret-key: AgB04k1+zH3K6pB2VcyJ//5UI5aWJwMVHlC/O7EC9UXoC4On2rSDLzgbhuYACkE+yZEn3l80/j163eYG9h+1uzCNgeYmZdnOm0B89tZO/6u/ZR+lnxSAHq+UTYgU/wVTHynRVcTYJRuzH0w/GZXCbTR5ukAtjBpW2PO6jDoY+vbGIyCHAK0rIRvoWTIpsbnTixk3OEmkkGMUf8R4dTzvxAb0KSHoi7kbCIb6smlrYKaIcgVM3TZylLooIhChEeg/G2pVIkBESIJDzuXLVbZETAm0Kt/bYFcvVKwqzhG7mlLWlv4LL7qpv5xl8hn1yYhir/jXDIMZtYQsjvaJOSxHBnuMZQ0JtY+HMvAwkV5XSW8wssCLySI5BSMz07CPHuD5o8Qa4W3gYQDch0Fawcmnjr46He0asRG+OWOTYJjeaQhmXM5mdL4Xqz2kQyKcu+tSkTS8HtIBx2v3GEaVc6yCyJYeDRzEqv4ufQTMSw3BxDoC9Fjib+Iwa4CDdzOh8FoGzyh+vCqiL1UqWm62fu6/ieer5J/kAP3CIPigcfS1kU1xYCEvGzBdhSXsfYyfzA6Z5Vz5RXVNJPL0krqqJYRfh6ChdE9tm88i7e0A/Cz3S3epUlck+YaqBdg1pkQZKSVYInDjwvCz4r7NIzRiXsDbmO1ebRtbg8DNZVILDuz3pVH84DRVQjtBVBRcNOGJ8deyLtih7fCTOaFTArCObLSnCB+hTv3UgX7DTpCX/OtYf5/lZw==
  template:
    metadata:
      creationTimestamp: null
      name: tandoor
      namespace: tandoor
