---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-credentials
  namespace: postgres
spec:
  encryptedData:
    postgres-password: AgC6FGv+vHNTgId5TEPjgHGjjguwxWKEW9oblmfBEaHh0Q48rD3im+jsKB+HzZVE0tDPiOvm1AO79yTZ2qJzzduZyStEfX7PwFox9R+9O9Oj9Lpmj+JX5rHTsRVQ7WuNzVop2BwCPFYQrqUavG+OKILbJuvvgLUaGO9UhItUAdu/fgDbIdb5znu86kU7tTHY1qEZLvpJT8f0AbQVI+YJPKB9zph5w5wjAJ7nOx7DOQ++Pm/MXOdoGAKIQuyeVmaGQXpdsZeEVXiVYyYxCsQB3JkB+7cYOdzpSC0QmhPIgqotFakHqMXJPhh2YZ7UUwtzRh8X9Z/SDYlZsiEZiJPdV2N8QkTvYzBZJTwomG4ptdrlErVtc1xr/IvLe8aV0bUbSV+4oh0gTTzglTtmrXfUXq0LCO3ra8apkWc9vM8PMYDRtULrKSnRuZn+0cW4lvHb/ByAtXqM/VcxHAIwJLWEkw6vEbsEHzPXQF+1Lg0bctXi4wCx7kK5mTajuqn9QjtVBQ6BHgLyjc3hgs1d638q05MK94e8IViQPQe7oQvhYEp68J0W41Z5DqWuP+KtH8yurb21/S6kM816JxKMGTnTuANpv/pIihRThiySOTBqrQAXeiUHh1VuD/hW7vF43s3Y5Yy5xseAWgdIyjnGGEEEFYF8wuWT6rIv/stiuN6nh4oGEHYKMH6/WibepGGPXeTUamCaEvwnty9nEu6nRdgNWd9rAE/2wLs6NDILGaBh49AveA==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-credentials
      namespace: postgres
