---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: postgres
spec:
  type: oci
  interval: 12h
  url: oci://registry-1.docker.io/bitnamicharts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres
  namespace: postgres
spec:
  interval: 30m
  chart:
    spec:
      chart: postgresql
      version: "16.4.1"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: postgres
      interval: 12h
  values:
    image:
      registry: ghcr.io
      repository: pschmidt88/bitnami-postgres-with-pgvector
      tag: v1.0.1
    primary:
      persistence:
        storageClass: local-path
        size: 5Gi
    metrics:
      enabled: true
    auth:
      existingSecret: "postgres-credentials"
    volumePermissions:
      enabled: true
