apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
  namespace: jellyfleet
  labels: &labels
    app.kubernetes.io/name: transmission
    app.kubernetes.io/component: media-automation
    app.kubernetes.io/instance: transmission
    app.kubernetes.io/part-of: jellyfleet
    app.kubernetes.io/version: "latest"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: transmission
      app.kubernetes.io/instance: transmission
  template:
    metadata:
      labels: *labels
    spec:
      nodeSelector:
        role: downloads-media
      initContainers:
        - name: gluetun
          image: ghcr.io/qdm12/gluetun:v3.40.0
          restartPolicy: Always
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          env:
            - name: TZ
              value: "Europe/Berlin"
            - name: VPN_SERVICE_PROVIDER
              value: "nordvpn"
            - name: VPN_TYPE
              value: "wireguard"
            - name: WIREGUARD_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: nordvpn-wireguard
                  key: private_key
            - name: SERVER_COUNTRIES
              value: "Germany"
            - name: FIREWALL_OUTBOUND_SUBNETS
              value: "10.0.0.0/8"
            - name: DNS_KEEP_NAMESERVER
              value: "on"
      containers:
        - name: transmission
          image: lscr.io/linuxserver/transmission:latest
          ports:
            - containerPort: 9091
              name: web
            - containerPort: 51413
              name: torrent
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Berlin"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
          livenessProbe:
            httpGet:
              path: /
              port: 9091
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: 9091
            initialDelaySeconds: 10
            periodSeconds: 20
            failureThreshold: 5
      volumes:
        - name: config
          hostPath:
            path: /data/configs/transmission
            type: DirectoryOrCreate
        - name: downloads
          hostPath:
            path: /data/torrents/downlodas
            type: DirectoryOrCreate
