apiVersion: v1
kind: Service
metadata:
  name: jellyfin-external
  namespace: external
spec:
  clusterIP: None
  ports:
    - name: http
      protocol: TCP
      port: 8096
      targetPort: 8096
---
apiVersion: v1
kind: Endpoints
metadata:
  name: jellyfin-external
  namespace: external
  labels:
    kubernetes.io/service-name: jellyfin-external
subsets:
  - addresses:
      - ip: 10.10.0.28
    ports:
      - name: http
        port: 8096
        protocol: TCP
