apiVersion: apps/v1
kind: Deployment
metadata:
  name: tika
  namespace: paperless
  labels: &labels
    app.kubernetes.io/component: tika
    app.kubernetes.io/name: paperless
spec:
  selector:
    matchLabels: *labels
  replicas: 1
  template:
    metadata:
      labels: *labels
    spec:
      containers:
        - name: tika
          image: apache/tika:3.0.0.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 1Gi
          ports:
            - containerPort: 9998
              name: gotenberg
      restartPolicy: Always
