---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: config
  labels:
    app.kubernetes.io/name: jellyseer
    app.kubernetes.io/component: config-pv
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.10.0.201
    path: /mnt/tank/k8s/configuration
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
  labels:
    app.kubernetes.io/name: jellyseer
    app.kubernetes.io/component: config-pv

spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
  volumeName: config
  storageClassName: ""
