apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless-ngx
  namespace: paperless
  labels: &labels
    app.kubernetes.io/component: paperless-ngx
    app.kubernetes.io/name: paperless
spec:
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      containers:
        - name: paperless-ngx
          image: ghcr.io/paperless-ngx/paperless-ngx:2.13.5
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 2
              memory: 4Gi
          env:
            - name: PAPERLESS_URL
              value: https://paperless.homelab.rookian.dev
            - name: PAPERLESS_REDIS
              value: redis://redis-master.redis:6379
            - name: PAPERLESS_DBHOST
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: host
            - name: PAPERLESS_OCR_USER_ARGS
              value: '{"continue_on_soft_render_error": true}'
            - name: PAPERLESS_TIKA_ENABLED
              value: "1"
            - name: PAPERLESS_TIKA_GOTENBERG_ENDPOINT
              value: http://gotenberg.paperless:3000
            - name: PAPERLESS_TIKA_ENDPOINT
              value: http://tika.paperless:9998
            - name: PAPERLESS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: paperless
                  key: secretKey
            - name: PAPERLESS_DBPASS
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: password
            - name: PAPERLESS_APPS
              value: "allauth.socialaccount.providers.openid_connect"
            - name: PAPERLESS_SOCIALACCOUNT_PROVIDERS
              valueFrom:
                secretKeyRef:
                  name: paperless
                  key: ssoConfig
            - name: PAPERLESS_SOCIAL_AUTO_SIGNUP
              value: "true"
            - name: PAPERLESS_DISABLE_REGULAR_LOGIN
              value: "true"
            - name: PAPERLESS_REDIRECT_LOGIN_TO_SSO
              value: "true"
          ports:
            - containerPort: 8000
              name: web

          volumeMounts:
            - name: data
              mountPath: /usr/src/paperless/data
            - name: media
              mountPath: /usr/src/paperless/media
            - name: consume
              mountPath: /usr/src/paperless/consume
            - name: import
              mountPath: /usr/src/paperless/import
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
        - name: media
          persistentVolumeClaim:
            claimName: media
        - name: consume
          persistentVolumeClaim:
            claimName: consume
        - name: import
          persistentVolumeClaim:
            claimName: import
      restartPolicy: Always
