---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: paperless
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.2
  storage:
    storageClass: local-path
    size: 1Gi
  enableSuperuserAccess: false
  bootstrap:
    initdb:
      database: paperless
      owner: paperless
  managed:
    roles:
      - name: paperless
        superuser: true
        login: true
