---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: nextcloud
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.2
  storage:
    storageClass: local-path
    size: 2Gi
  enableSuperuserAccess: false
  bootstrap:
    initdb:
      database: nextcloud
      owner: nextcloud
  managed:
    roles:
      - name: nextcloud
        superuser: true
        login: true
