---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 1h
  url: https://nextcloud.github.io/helm/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  chart:
    spec:
      chart: nextcloud
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: nextcloud
      version: 8.0.1
  install:
    timeout: 10m
  upgrade:
    timeout: 10m
  interval: 1h0m0s
  releaseName: nextcloud
  targetNamespace: nextcloud
  values:
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql
      existingSecret:
        enabled: true
        secretName: postgres-app
        usernameKey: user
        passwordKey: password
        hostKey: host
        databaseKey: dbname
    nextcloud:
      host: nextcloud.homelab.rookian.dev
    redis:
      enabled: true
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-dns
      tls:
        - hosts:
            - nextcloud.homelab.rookian.dev
          secretName: tls-nextcloud-homelab
    persistence:
      enabled: true
      storageClass: local-path
      nextcloudData:
        enabled: true
        existingClaim: nextcloud-data
    metrics:
      enabled: true
