---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-nfs-pv
  namespace: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud-data
    app.kubernetes.io/component: data-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.10.0.201
    path: /mnt/tank/nextcloud-data
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
  namespace: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud-data
    app.kubernetes.io/component: data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  volumeName: nextcloud-nfs-pv
  storageClassName: ""
---
