---
apiVersion: v1
kind: Namespace
metadata:
  name: postgres
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cnpg 
  namespace: postgres
spec:
  interval: 1h
  url: https://cloudnative-pg.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: postgres
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.23.0"
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: postgres
      interval: 12h 
