---
apiVersion: v1
kind: Namespace
metadata:
  name: kubedb
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: appscode
  namespace: kubedb
spec:
  interval: 24h
  url: https://charts.appscode.com/stable/
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: appscode-license
  namespace: kubedb
spec:
  encryptedData:
    key.txt: AgDTa1W5DN6Y4atkk8dEOEi//Kh6B7rWiCgTUGOxKrPbpRrXCZxEI39XHjRbGFpvL0hHJQn9jb0VHqBInbXPGWdZt8trY0K7UipFeTGABWuYomoXQ/KVjE6VWQShrSdik9Jnod9qF7X82Ri6Iqa/8tgvc409I0Ja/BaYO3eC8TOVSlf8wgUxvgl6vClXf+HNqkRucbnPwFZNz2fAmiNnozMiscHxj2JHnEEEjGTgjDkg7Z3PvfIBolBTetFlu49mlrMrh1OGNvaIT9A9rpxb+23P1YzQBxuAAhT52c/BvPXC3VJqHGaSlutzZcXRXU+UrFvTjgpCk1uTPssHkcSb5baV8XkVFMhIUiutwrtebYukP8TIWb7Q7sJcApYrR0p4bNv5in8NBe4WW9uooQwf/E8/BKnLFz8BrNnw6jAq9cW9/OTLk8NofeBVTpwLeoXL6ZQkLpzdKMeoRqs45dYuf+16Kj+8YeKX2y+YZXyNgLZU+eQhp0YOTdyB2bdniPH1bkx1I7BeZ5sZBRuSkLAKhR9FhzR0ryclRHObWkP9WdsSnqvutwgouTLXY/lMncpwZoNohQiF+SzmYMdl8tFr8IjDrVEHPNo2SAQp/aTrnwIyx/dOx1yuK27LSU8MjKy7CYx9uI6rDlBit907f+nE+Allh3E6i6n/mbM8ngdmQLncyUl9oOtRTRnrZuqVhVV3PPMWNGsQS3Q+z/gsI3VS5GrVn2DonzmAw0GbdjBeJtKP3nnqvvKwrIYem8mCV/0MzQ4ZFBsM3IdVK7Kvad4vwboyYQ/E9/pM2JxBt1eqg9nq7V/VeFeTSLYSAdTa1yLBCzimOpB0qKEJ8lde/xFHlpwxb/M5gVvpYF6Wlp9A6iBcWCyvtr5bPsbPID0ZRmOi8/X0v8+myRUXzqxJLb088hCbgFElw2uLoS1/9Vrb+UUcLH5wortLRjp1MujCxq447DkPCyMxsaCNOxWp9G65jPHeDN1aenTw39D19Fy4OFPzYLUtpv9CWNCepxuZYgxPZ984SME2WfiYG8aAgvXA57Ufp8YnzJqrfsCiCiMtJ/X3pJAAliVcUDHzLc71cIc3+Yy4Cq3XUmxXpKasY9wDCck1RJV0QfyZ90P6AWdURyR51P9Nnne9Q+Kx7p3OaSG7jHyq7w8Igz2OLaCXn5KNzdAgHvO2z73PjiKkAXg1x9/MV6XLEArRdvzNhB0lbGjY3cxTVPGj5RLvDxfZ/igun3ZIH8Gft90wXr+2bxMjfGOd01f9yIaQtUxqgj/tqj0emMX5PiePasPi1BVN4kktmPcyteBcX7rq2ye077RyF7JQ/H0DZNfZvjMCVqdXWF2g19TpgSrgsdHbKbXTi/eZjpWNn1WPcFId6S48byItM5o40/QRwKo97cXvtnHGu0P5+AL9j23oor+RUJKI9F46tb7xW63vnb2Q7z13fB32VHzFPDl50B5TLyy8MLQYvsfM542H1c0EJc0R8hLeRGJYnmg5EgzfmsEkbjE7J8RUpW/fYNXC7b3AqYLl90rDFfJRQNgWJn8AuFrjRgCAG+LuwDlj6epU6GYTFdM9j3gmgDoZco6r96GQUI7EyAp8czmgb9cT3owGW0yXP2eEX82Y+Hi7WoNZ1iZ5UQaw23NCrjGCvg7L/pQo8eZ4VLCId65Bi5V1UQEemWv6kUmkoir5vZQMz7lgqlhliHhtkeY1dLIUQjHrvpNomn/G9XmsPiY1hQjyL/VwRSrPW5mQaxMU+y9YOAs0pz0FXe6y9hiyaeu9IZJb2PhEVwUgsHcy8ujNWv88vfXSRvTXcLaCdKi/CJvlBpkoRX1j+bpA4dNeYMJi+/zki1Nh3TQSV3ozyAB6DhKqjUe5YEoYDBu2PSU0hDXfJw1Zi4Aat4W2AolpaS975iyPS9jaR9Fe2BD9Gi7zuz4DZARFEaYvZSSz6Co2xW40Zk3J3SMkEZeKFIOoMDs+OyC8iar+PuTUuT5qxLWHVHDS21pqpDiYErdUzK7uDH4Y9cE4qn2WnQOrsDqcjqhGTw8QNkSr6uxCYYVdQ5XlhawDC60wmKrhtdv0SlwOoCPqpGh7ngS8Kmdrcwdd09TbWKMD0T5/HYukKFuDQiK7xwvprZuAOm3BGVlH9tBcCBH0/h8zlBgzhx3tOwGMy0BGYmH9okQ+hsxun/ZzcdQahMCDK0WvYG4Zk3Amk+N61xZcxAQ/ltrqRsbIYcOo+sLil1X3sDt7z5ilyGk+DZwdtAu6NBdr0rSBzgYf1lq5fiJpKraV7mUI/W7Iaj2atAX7Dl15hYwwOqmGPrGOBYtnu1+EZiB4Qf3jEqTEGcEnXT7gFX3XSi2l15E+6pFCVo2rulkl1+SrSM/cEoU19qoOLmHbM4TZwADbegqVKmbnKZk4kO3fz5NNb96Zq8mNxAEmjpYi6u18E/fT0zUVy1JPYiDKACrtOeOrem3ClYVGQYyKMY7/NfdWMRBfJUwpjoK0z2ye6bfK7kmS153zGca8lSNTR6Zhk2z5SDBoAfkI+4mXa8wlSWJYe+CaL6StrlbRD8f9c4iDmjUeQOz93GITpaGNMXZ+wlupT/S7U1naaMtRT2DhK3ujzmMW3TPL3OrEqCJIJEt86H3pZd7g9g97eC0cYhK3IfeEURA8rLZ0+ccRQ/RGzoCbWxAwN7g1icfNsyooEuI7NjU3kGWFa+lsx1LVXwJ+oMxuDcH9d0O29NW/3JAYeCZ3SVQr9z2zbcK0FBGBn8PS/SDtXYLxgyRH6e5hGed6mWBzsX7R7wbsQJl16sFjS+KinRqz9SOxkAnNyCsPuuIrRBCDxADJ3PfLzWQJ4aNwzeB1zX/as/lA8M7lXUE1nVvdy5WFfWp3/FfTeJmwAg==
  template:
    metadata:
      creationTimestamp: null
      name: appscode-license
      namespace: kubedb
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubedb
  namespace: kubedb
spec:
  interval: 30m
  chart:
    spec:
      chart: kubedb
      version: "2025.1.9"
      sourceRef:
        kind: HelmRepository
        name: appscode
        namespace: kubedb
      interval: 12h
  values:
    global:
      licenseSecretName: appscode-license
