apiVersion: batch/v1
kind: CronJob
metadata:
  name: auto-stack
  namespace: immich
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: auto-stack
              image: ghcr.io/tenekev/immich-auto-stack:latest
              args: ["/script/immich_auto_stack.py"]
              env:
                - name: API_URL
                  value: http://immich-server:2283/api
                - name: API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: api-keys
                      key: autostack-api-key
                - name: SKIP_MATCH_MISS
                  value: "true"
                - name: CRITERIA
                  value: |
                    [
                      {
                        "key": "originalFileName",
                        "regex": {
                          "key": "([A-Z]+[-_]?[0-9]{4}([-_][0-9]{4})?)([\\._-].*)?\\.[\\w]{3,4}$",
                          "index": 1
                        }
                      },
                      {
                        "key": "localDateTime"
                      }
                    ]
          restartPolicy: OnFailure
---
