---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: immich
spec:
  instances: 1
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16.5-v0.3.0
  # Persistent storage configuration
  storage:
    storageClass: local-path
    size: 10Gi
  enableSuperuserAccess: true
  bootstrap:
    initdb:
      database: immich
      owner: immich
  managed:
    roles:
      - name: immich
        superuser: true
        login: true
  postgresql:
    shared_preload_libraries:
      - "vectors.so"
