---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media
  namespace: immich
  labels:
    app: immich
spec:
  capacity:
    storage: 1Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - rw
  hostPath:
    path: /media/immich
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
selector:
  matchLabels:
    app: immich
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: immich
  labels:
    app.kubernetes.io/name: data-pvc
    app.kubernetes.io/instance: immich
    app.kubernetes.io/component: data-storage
    app.kubernetes.io/part-of: immich
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
