---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: library
  namespace: immich
  labels:
    app.kubernetes.io/name: library
    app.kubernetes.io/component: library-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.10.0.201
    path: /mnt/tank/photos
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: library
  namespace: immich
  labels:
    app.kubernetes.io/name: library
    app.kubernetes.io/component: library-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: library
  storageClassName: ""
---
