---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media
  namespace: immich
  labels:
    type: local
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /media/immich
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich
  namespace: immich
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Ti
selector:
  matchLabels:
    type: local
