---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: immich
  labels:
    app.kubernetes.io/name: data-pvc
    app.kubernetes.io/instance: immich
    app.kubernetes.io/component: data-storage
    app.kubernetes.io/part-of: immich
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
