---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-keys
  namespace: immich
spec:
  encryptedData:
    autostack-api-key: AgAIzMIzHHaoSZoyYciGKwfWbxbeGcgFpA7XqfgB+n+CL3I/4z5YmsLI3orVMw1iLCb/FSh88yCms3l/eyV/SzAkNkn3QR1USAeS7cbQ9AM5M0+fMO/U8wNGUdf7oEScHbs5UaGv4ObGclVrT0Z4vTgIvEfqC7oIKCH/VR7n8fyigclzX7pxXEeLan4OvyP+krrcl0P0MiZGWf+1r9tTwVtJhYhzw+2NYrSRzpmsvlUIc3pcMR1oLcEkg0xpgdd3PZs059I0PyThNsRLVYR2pDLyz8f3kmiVbCF4VeuVqHiFcegBOEb5ou2od9V2VgpT65Fyfr/wkiFW+DDMzGmPow1alM+yOeiuKEX3s0TBXrRcVtByymSL7jMj0IrhnqbI1aHrYKNH6C9bxCq4hqJHmDep8Vv9qr20thYA01eNbsIwcY9YgAY5Pikr+EAkHF8ibQsQpzW1xRXSUbeBg4V3kaWdq37gI7ICsC4SQZzA+dgaVdUXdnXA2E9NKwBtPUdLbSM3ujFVPorQVuRbGhogNnflXE0NMXje72TphtzFEqa9xIRTm3abGyKaH1NrznEhxXGO2Iay1ZhCdMYEDBk4jZHf3wwzJzRkxWnxB/1gSMR9uJhC2Cdo+7zVAdhiPPKyhpBkcGcuW5eI2KC3qcMt9V9nnNYVnbeFsw9Hft0crf13Bq2sDTorhZ8+rT3dgKg+JK9ayP3sE1K9lvK4FXfoUCaolaNJMcC4zwdfDpcKE2wbvjipY8XL2m7bIns+
  template:
    metadata:
      creationTimestamp: null
      name: api-keys
      namespace: immich
