---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: navidrome
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
