apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkwarden
  namespace: linkwarden
  labels: &labels
    app.kubernetes.io/name: linkwarden
    app.kubernetes.io/component: bookmarks
    app.kubernetes.io/instance: linkwarden
    app.kubernetes.io/part-of: linkwarden
    app.kubernetes.io/version: "latest"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: linkwarden
      app.kubernetes.io/instance: linkwarden
  template:
    metadata:
      labels: *labels
    spec:
      containers:
        - name: meilisearch
          image: getmeili/meilisearch:v1.21.0
          imagePullPolicy: IfNotPresent
          env:
            - name: MEILI_MASTER_KEY
              secretKeyRef:
                name: linkwarden
                key: meili-secret-key
        - name: linkwarden
          image: ghcr.io/linkwarden/linkwarden:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: uri
            - name: NEXT_PUBLIC_AUTHENTIK_ENABLED
              value: "true"
            - name: AUTHENTIK_ISSUER
              value: "https://sso.homelab.rookian.dev/application/o/linkwarden"
            - name: AUTHENTIK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: sso-secrets
                  key: client-id
            - name: AUTHENTIK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: sso-secrets
                  key: client-secret
            - name: NEXTAUTH_URL
              value: "https://linkwarden.homelab.rookian.dev/api/v1/auth"
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: linkwarden
                  key: nextauth-secret-key
            - name: MEILI_MASTER_KEY
              secretKeyRef:
                name: linkwarden
                key: meili-secret-key
            - name: MEILI_HOST
              value: meilisearch
          ports:
            - containerPort: 3000
              name: http
      restartPolicy: Always
---
