---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secrets.yaml
  - sso-secrets.yaml
  - database.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
