---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgC/kVNZqkBP7QfzmEvJg0RW1vVcGQRFQD1HmJvMWvGghLf24IvrYDUmiihY/CDpJyhS97oCuEQ03K5K7xgMns8yPDnopMy09vu3uk5EisFanK2IcQFK7inwWNSoRJ37HVVjb5KyM7UK4ihOc+QHMCJc5pWGqGvzrGwbxF9xz/JsruyWe6oTq5zKEL16mX8XeuHvoMzH5EzhCUEnTVD0QS7VrwPAnOjrURUO5fLlbqS3uzCTGnD+QCsylUxzp7xLOFuLFQErC4dc21dNzPBpdLmVoC8+GUUf2zxz1xpCH9Tle6C9pIq9QjruU4+klpH05UxywdIPpedYQXQDWqxLOvkwypEPU6tKTZPvLWxZMyYY1gwJAmmyCtdEl//tNa2BL519An0sY62Ziw+3i+xeeFWluWtcuKZ89Pt3NDdwGgOpNEXzSq4Yvz1ThtykPwTtlqK5kkJNtk8wVr2YJhT+3PwDEE1AC89C5wVLczjddZSBo7+fGNxKVJkGF2mvRYxzjYu+cg33+SO8RZKG+O9hWqfs+kaQsnY6UzXUJ2c0eVTF3KChPcMF7X+SFVd9W4UGb78H27us5meBoNbQt0256r/4aEAJ1XwVWLqNvuEMbqkO4k5Alo67ERq3KmnOJioBiQhoR4K+BGCzAHwNVgwGXz+FI6KboBXxviYnBChi0jvzGMvqF9bLVOEiTsj7f7SWLDUkOZHMrj5YqFgvaEa+rL7l14xde5C5sycx4GsPhWzYRNu1/psttbtH
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api
      namespace: cert-manager
