---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAzSvYPreZB3JKqxCN9JsFNr0/oQ6v9atU5bLu/zdy/E1g47XbpVy0bGDsJYIhy7FCwM48zDIxDbKTOuHVDt/oPhZ3GGZZVnifkeqZ+Gwr9wMK4m5z5y6FkOAGQAIRstIw4THeUrZET5pqcv21R/MLLtgC2OeOwCxJwcxDGbsZu+9X1ybUN50m5jDACLZxYzekwwh/FuSgjWfoTjH8HKwLccW2p1jOYNlKcRczGE1xp0a+uVrABldeJZEP7d7lBOSykLgHDfqZ0vIwj5waqZdh3dWpUswblYP4zxUx/eJLMnikBSqd79qLW1ktmsA+KV/8hsglUCNJSNY1LYxKAGftoByPKjhWEEddbN4QVoX9kuGibO3eqIECL4MefgWqQlrc4WvYZfMX9BDCu413HjSfV3hKOQXo77ZRxO33V01TmP4Sms0qPe0pQYnepi7qOGCXX52n0NZ/GGDQMsXLGKpujzOJdHl1T/MnOwxBpJ+5FU7A4Y5rOIu6P0vMfWPdfctr0WSdXRZMmMfEzIHXeaUFY6dvxhiBp2hXY5lXr0kpvFBHb3Xe8x50/ZF/k7rENTm5dJ3LID/exUoO92QuRHYSsxrkmXIQDPK1x01eNRiVWFvcN31nJdwpbPUuncPm74URNxStOSPah0oNSA3E0H6FPTs6U2uliU3sRxWcbxxwGxuB6qxwrgqCnvr9782CbiobFqBDc2VtqkF7rD2qyxDANpSyvW4QxBGLnTar8CXQ8rDSkDK5PtTUR
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api
      namespace: cert-manager
