---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBM4RV+FyWtgLXZY6B51ECiJIi6BxdRGLV8AGXC4+UBF1lMYjMP0GYZYKZ3mfXPHMkdH7CFceU+wBqWyKqfNfLsiOh0wvlfR1RHyC8AaMbDcjR10ErxH8BJhbozP8HtUSI94eRLY7W93G9tCJH8S0+6r3GQdMRK2j260jE+xQCcxB+SDC2Y3F74viqEADVPArfhf+0VzSvUz5PbTP+UPLNDDbBEz7QVJG1AtYFE19C91rCgjYyNXHsCsgE+u3XCEc7xQRYkXY12q8slZ27g39UMMNsA6K3uPfykfc1dn/Or++vwINwmNxj4RYIbrcIbN2ofqct7P+nRw6BG/TmP6j/FrJRSwgYaUk6EOUjtrz/q5uyjKyB92i2iNG/05MKaHlXA+vFX1y+KUZEfIRiyWP6xVD4HJ9DIJSM4gd/UOrz4lz6fq/Hx6NempbMWKa62Dzw5UAOas3oRwfZn/W1wN2DqURdE1WSiW1bLOQeVz/+HGy0+izTmDMOFvEStLamxjG+Tz/KdhVALmwqW8uZobiksNnhUKAedjFLpPpJMNIrhC/5EXzXDTERLcDYEQSG2I1/kLTW8WpMCKW6yBSF7eQRuIXqKXMZ/5uLhyJkQNRuMNJrwrS7FGp3CJUTCIFQeqplnKDC9BO7I3pddxxka9rEECLp18A9IB5GyNicCU9YM9XuREakYf19OKMTe+t3kx2WkrKSQsh7eMMIIGE0EBSqukDPnCSphYLvNGFpSefG5TebVyVCnkq2q
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api
      namespace: cert-manager
