apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: kubernetes-secretstore
  namespace: postgres
spec:
  provider:
    kubernetes:
      remoteNamespace: postgres
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: cnpg-cloudnative-pg
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-credentials
  namespace: postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: kubernetes-secretstore
  target:
    name: postgres-credentials
    template:
      engineVersion: v2
      data:
        POSTGRES_HOST: "{{ .host }}.postgres.svc"
        POSTGRES_USER: "{{ .user }}"
        POSTGRES_PASS: "{{ .password }}"
        POSTGRES_URI_ARGS: ""
  dataFrom:
    - extract:
        key: postgres-app
