---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: postgres
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.2
  storage:
    storageClass: local-path
    size: 1Gi
  enableSuperuserAccess: true
  bootstrap:
    initdb:
      database: postgres
      owner: postgres
