---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - nordvpn-wireguard.yaml
  - jellyseerr
  - sonarr
  - radarr
  - prowlarr
  - flaresolverr
  - transmission
