---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: goauthentik
  namespace: authentik
spec:
  interval: 1h
  url: https://charts.goauthentik.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  chart:
    spec:
      chart: authentik
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: goauthentik
      version: 2024.12.2
  install:
    timeout: 10m
  interval: 1h0m0s
  releaseName: authentik
  targetNamespace: authentik
  values:
    authentik:
      postgresql:
        host: file:///postgres-creds/host
        name: file:///postgres-creds/dbname
        user: file:///postgres-creds/user
        password: file:///postgres-creds/password
      secret_key: file:///application-secrets/key
      redis:
        host: redis-master.redis.svc.cluster.local
    server:
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-dns
        hosts:
          - sso.homelab.rookian.dev
        tls:
          - hosts:
              - sso.homelab.rookian.dev
            secretName: tls-sso-homelab
      volumes:
        - name: secrets
          secret:
            secretName: authentik-secrets
        - name: postgres-creds
          secret:
            secretName: postgres-app
      volumeMounts:
        - name: postgres-creds
          mountPath: /postgres-creds
          readOnly: true
        - name: secrets
          mountPath: /application-secrets
          readOnly: true
    worker:
      volumes:
        - name: secrets
          secret:
            secretName: authentik-secrets
        - name: postgres-creds
          secret:
            secretName: postgres-app
      volumeMounts:
        - name: postgres-creds
          mountPath: /postgres-creds
          readOnly: true
        - name: secrets
          mountPath: /application-secrets
          readOnly: true
