---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: authentik
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.2
  storage:
    storageClass: local-path
    size: 1Gi
  enableSuperuserAccess: false
  bootstrap:
    initdb:
      database: authentik
      owner: authentik
  managed:
    roles:
      - name: authentik
        superuser: true
        login: true
