apiVersion: v1
kind: Service
metadata:
  name: flaresolverr
  namespace: jellyfleet
  labels:
    app.kubernetes.io/name: flaresolverr
    app.kubernetes.io/component: media-automation
    app.kubernetes.io/instance: flaresolverr
    app.kubernetes.io/part-of: jellyfleet
spec:
  selector:
    app.kubernetes.io/name: flaresolverr
    app.kubernetes.io/instance: flaresolverr
  ports:
    - port: 8191
      targetPort: 8191
      protocol: TCP
