apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
  namespace: jellyfleet
  labels:
    app.kubernetes.io/name: sonarr-config
    app.kubernetes.io/component: configuration
    app.kubernetes.io/part-of: jellyfleet
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  volumeName: sonarr-config-pv
