apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-config-pv
  labels:
    app.kubernetes.io/name: sonarr-config
    app.kubernetes.io/component: configuration
    app.kubernetes.io/part-of: jellyfleet
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.10.0.201
    path: /mnt/tank/k8s/configuration
