---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config-pv.yaml
  - config-pvc.yaml
  - media-pv.yaml
  - media-pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
