---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: redis
  name: redis
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: redis
spec:
  type: oci
  interval: 1h0m0s
  url: oci://registry-1.docker.io/bitnamicharts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: redis
spec:
  chart:
    spec:
      chart: redis
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: 20.6.3
  interval: 1h0m0s
  releaseName: redis
  targetNamespace: redis
  values:
    metrics:
      enabled: true
    architecture: standalone
    auth:
      enabled: false
    master:
      persistence:
        storageClass: local-path
      pdb:
        create: false
    networkPolicy:
      enabled: false
    serviceAccount:
      create: false
    volumePermissions:
      enabled: true
