---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: grafana-github
  namespace: monitoring
spec:
  interval: 1h
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  chart:
    spec:
      chart: grafana
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana-github
      version: 8.15.0
  interval: 1h0m0s
  releaseName: grafana
  targetNamespace: monitoring
  values:
    persistence:
      enabled: true
      persistence: pvc
      storageClassName: local-path
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-dns
      hosts:
        - grafana.homelab.rookian.dev
      tls:
        - hosts:
          - grafana.homelab.rookian.dev
          secretName: tls-grafana-homelab
